In [1]:
import numpy as np

In [2]:
def Value_Iteration_Prediction(P_pi, c_pi, gamma, tol = 1e-8):
    
    k = 0
    J_prev = np.ones([P_pi.shape[0], 1])
    J = np.zeros([P_pi.shape[0], 1])
    
    while np.linalg.norm(J_prev-J) >  tol:
        J_prev = J
        J = c_pi + gamma*np.matmul(P_pi, J)
        k += 1

    print(k)
    return J

In [3]:
def Value_Iteration_Control(P, c, gamma, tol = 1e-8):
    
    k = 0
    J_prev = np.ones([P.shape[1], 1])
    J = np.zeros([P.shape[1], 1])
    
    while np.linalg.norm(J_prev-J, np.inf) >  tol:
        J_prev = J
        J = c + gamma*np.matmul(P, J)
        
        pi = np.isclose(J, np.min(J,axis = 0)).astype(int)

        pi = pi/np.sum(pi, axis = 0)
        
        J = np.min(J, axis=0)
        
        k += 1
        
    pi = np.concatenate(pi, axis = 1)
    
    print(k)
    return (pi,J)
    return J

In [4]:
def Policy_Iteration(P, c, gamma):
    
    pi = np.ones(c.shape)/c.shape[0]
    pi_prev = np.ones(c.shape)
    
    k = 0
    
    while not np.allclose(pi,pi_prev):
        
        pi_prev = pi
        
        P_pi = np.sum(P*pi, axis = 0)
        c_pi = np.sum(c*pi, axis = 0)
        
        J = np.matmul(np.linalg.inv(np.eye(P_pi.shape[0]) - gamma*P_pi), c_pi)
        
        Q = c + gamma * np.matmul(P,J)
        
        pi = np.isclose(Q, np.min(Q,axis = 0)).astype(int)

        pi = pi/np.sum(pi, axis = 0)
        
        k += 1
        
        
    pi = np.concatenate(pi, axis = 1)

    print(k)
    
    return pi

In [5]:
n = [9,9]

Pup = np.zeros(n)
Pdown = np.zeros(n)
Pleft = np.zeros(n)
Pright = np.zeros(n)

Pup[2,-2] = Pdown[2,-2] = Pleft[2,-2] = Pright[2,-2] = 1
Pup[3,-1] = Pdown[3,-1] = Pleft[3,-1] = Pright[3,-1] = 1
Pup[-1,-1] = Pdown[-1,-1] = Pleft[-1,-1] = Pright[-1,-1] = 1
Pup[-2,-2] = Pdown[-2,-2] = Pleft[-2,-2] = Pright[-2,-2] = 1

Pup[0,0] = Pup[1,1] = Pup[4,0] = Pup[5,1] = Pup[6,2] = 1 
Pdown[0,4] = Pdown[1,5] = Pdown[4,4] = Pdown[5,5] = Pdown[6,6] = 1
Pleft [0,6] = Pleft[1,6] = Pleft[4,4] = Pleft[5,5] = Pleft[6,4] = 1
Pright[0,2] = Pright[1,3] = Pright[4,6] = Pright[5,6] = Pright[6,0] = 1

P = np.array([Pup, Pdown, Pleft, Pright])

c = np.array([0.1, 0.1, 0, 1, 0.1, 0.1, 0.1, 0, 0])
c = np.reshape(c, [9,1])

cost = np.array([c,c,c,c])

In [6]:
Value_Iteration_Control(P, cost, 0.9)

3


(array([[0.  , 0.  , 0.  , 1.  ],
        [0.  , 0.  , 1.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.  , 0.  , 0.5 ],
        [0.  , 0.  , 0.  , 1.  ],
        [1.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, 0.25]]),
 array([[0.1 ],
        [0.19],
        [0.  ],
        [1.  ],
        [0.19],
        [0.19],
        [0.1 ],
        [0.  ],
        [0.  ]]))

In [7]:
Policy_Iteration(P, cost, 0.9)

2


array([[0.  , 0.  , 0.  , 1.  ],
       [0.  , 0.  , 1.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.5 , 0.  , 0.  , 0.5 ],
       [0.  , 0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

In [11]:
Value_Iteration_Prediction(P[2], cost[2], 0.9)

162


array([[0.99999996],
       [0.99999996],
       [0.        ],
       [1.        ],
       [0.99999996],
       [0.99999996],
       [0.99999996],
       [0.        ],
       [0.        ]])

In [12]:
0.1+0.1*0.9/0.1

1.0